sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
<<<<<<< HEAD
    password: "123456"
=======
    password: root
>>>>>>> 93f49a209534d625b3f89bdb57c9914d79a2056e
